# Universal prompt
format = """[┌─](bold green)$username$hostname$all[│](bold green)
$character"""

# Inserts a blank line between shell prompts
add_newline = false 

# Make prompt single line
[line_break]
disabled = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[└─❯](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖](bold red)"

# Username
[username]
format = "[\ue0b6](fg:#202db8)[$user]($style)[\ue0b0](fg:#202db8)@"
style_root = "bold #ff0000"
style_user = "bg:#202db8"
show_always = true

# Hostname (computer name)
[hostname]
format = "[\ue0b6](fg:#33aa33)[$hostname]($style)[\ue0b0](fg:#33aa33) in "
style = "bg:#33aa33"
ssh_only = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
